spring.application.name=Comentarios-Seguimiento
spring.datasource.url=jdbc:mysql://localhost:3306/MSComentario?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=Villita71

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true